[project]
name = "ct-tools-mod"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pymel>=1.5.0",
    "pyside6>=6.9.2",
    "qt-py>=1.4.6",
    "types-maya-strict>=2025.0.6",
]
