# 常量定义
FKIK_ATTRS = [
    "armUI_L0_ctl.arm_blend",
    "armUI_R0_ctl.arm_blend",
    "legUI_L0_ctl.leg_blend",
    "legUI_R0_ctl.leg_blend",
]
# 骨骼和控制器约束映射
SKELETON_TO_CONTROLLER_MAP = {
    "root": "root_main_C0_ctl",
    "pelvis": "body_C0_ctl",
    "spine_01": "spine_C0_fk0_ctl",
    "spine_02": "spine_C0_fk1_ctl",
    "spine_03": "spine_C0_fk2_ctl",
    "spine_04": "spine_C0_fk3_ctl",
    "neck_01": "neck_C0_fk0_ctl",
    "neck_02": "neck_C0_fk1_ctl",
    "head": "neck_C0_head_ctl",
    "clavicle_l": "clavicle_L0_ctl",
    "upperarm_l": "arm_L0_fk0_ctl",
    "lowerarm_l": "arm_L0_fk1_ctl",
    "hand_l": "arm_L0_fk2_ctl",
    "weapon_l": "weapon_L0_ctl",
    "thumb_01_l": "thumb_L0_fk0_ctl",
    "thumb_02_l": "thumb_L0_fk1_ctl",
    "thumb_03_l": "thumb_L0_fk2_ctl",
    "index_metacarpal_l": "index_metacarpal_L0_ctl",
    "index_01_l": "index_L0_fk0_ctl",
    "index_02_l": "index_L0_fk1_ctl",
    "index_03_l": "index_L0_fk2_ctl",
    "middle_metacarpal_l": "middle_metacarpal_L0_ctl",
    "middle_01_l": "middle_L0_fk0_ctl",
    "middle_02_l": "middle_L0_fk1_ctl",
    "middle_03_l": "middle_L0_fk2_ctl",
    "ring_metacarpal_l": "ring_metacarpal_L0_ctl",
    "ring_01_l": "ring_L0_fk0_ctl",
    "ring_02_l": "ring_L0_fk1_ctl",
    "ring_03_l": "ring_L0_fk2_ctl",
    "pinky_metacarpal_l": "pinky_metacarpal_L0_ctl",
    "pinky_01_l": "pinky_L0_fk0_ctl",
    "pinky_02_l": "pinky_L0_fk1_ctl",
    "pinky_03_l": "pinky_L0_fk2_ctl",
    "clavicle_r": "clavicle_R0_ctl",
    "upperarm_r": "arm_R0_fk0_ctl",
    "lowerarm_r": "arm_R0_fk1_ctl",
    "hand_r": "arm_R0_fk2_ctl",
    "weapon_r": "weapon_R0_ctl",
    "thumb_01_r": "thumb_R0_fk0_ctl",
    "thumb_02_r": "thumb_R0_fk1_ctl",
    "thumb_03_r": "thumb_R0_fk2_ctl",
    "index_metacarpal_r": "index_metacarpal_R0_ctl",
    "index_01_r": "index_R0_fk0_ctl",
    "index_02_r": "index_R0_fk1_ctl",
    "index_03_r": "index_R0_fk2_ctl",
    "middle_metacarpal_r": "middle_metacarpal_R0_ctl",
    "middle_01_r": "middle_R0_fk0_ctl",
    "middle_02_r": "middle_R0_fk1_ctl",
    "middle_03_r": "middle_R0_fk2_ctl",
    "ring_metacarpal_r": "ring_metacarpal_R0_ctl",
    "ring_01_r": "ring_R0_fk0_ctl",
    "ring_02_r": "ring_R0_fk1_ctl",
    "ring_03_r": "ring_R0_fk2_ctl",
    "pinky_metacarpal_r": "pinky_metacarpal_R0_ctl",
    "pinky_01_r": "pinky_R0_fk0_ctl",
    "pinky_02_r": "pinky_R0_fk1_ctl",
    "pinky_03_r": "pinky_R0_fk2_ctl",
    "thigh_l": "leg_L0_fk0_ctl",
    "calf_l": "leg_L0_fk1_ctl",
    "foot_l": "leg_L0_fk2_ctl",
    "ball_l": "foot_L0_fk0_ctl",
    "thigh_r": "leg_R0_fk0_ctl",
    "calf_r": "leg_R0_fk1_ctl",
    "foot_r": "leg_R0_fk2_ctl",
    "ball_r": "foot_R0_fk0_ctl",
}
